
name: OrderBook
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    hyperfuel_config:
      url: https://fuel-testnet.hypersync.xyz
    contracts:
      - name: Registry
        address: 0x194987ad2314d2de50646078ac1841f00b2dffda863a7d3dd421d220eb83d019
        abi_file_path: ./abis/registry.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: MarketRegisterEvent
      - name: Market
        abi_file_path: ./abis/market.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: DepositEvent
          - name: DepositForEvent
          - name: WithdrawEvent
          - name: WithdrawToMarketEvent
          - name: OpenOrderEvent
          - name: CancelOrderEvent
          - name: TradeOrderEvent
