
name: OrderBook
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    hyperfuel_config:
      url: https://fuel-testnet.hypersync.xyz
    contracts:
      - name: Registry
        address: 0xfc3439e66c15c0b8e8e02e0fe4951eecd6001639a6aa8a650885af62ea92540f
        abi_file_path: ./abis/registry.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: MarketRegisterEvent
      - name: Market
        abi_file_path: ./abis/market.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: DepositEvent
          - name: WithdrawEvent
          - name: OpenOrderEvent
          - name: CancelOrderEvent
          - name: TradeOrderEvent
