name: OrderBook
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    hyperfuel_config:
      url: https://fuel-testnet.hypersync.xyz
    contracts:
      - name: Registry
        address: 0xd6474c9d90a4a4bcdb762f48d38afc8283799799d7e48e1055fb373ff87fb9d7
        abi_file_path: ./abis/registry.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: MarketRegisterEvent
      - name: Market
        abi_file_path: ./abis/market.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: DepositEvent
          - name: WithdrawEvent
          - name: WithdrawToMarketEvent
          - name: OpenOrderEvent
          - name: CancelOrderEvent
          - name: TradeOrderEvent
