name: OrderBook indexer
networks:
  - id: 0
    start_block: 0
    hypersync_config:
       url: https://fuel-testnet.hypersync.xyz
    contracts:
      - name: OrderBook
        address: 0xd657825f4ee50d704740af011bd6885f1939071767de83d931f7482093da2f60 
        abi_file_path: ./abis/spark-orderbook.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: OpenOrderEvent
          - name: CancelOrderEvent
          - name: TradeOrderEvent
          - name: DepositEvent
          - name: WithdrawEvent
