name: OrderBook indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    hyperfuel_config:
       url: https://fuel-testnet.hypersync.xyz
    contracts:
      - name: OrderBook
        address: 0xb1ed073b4dccbff48e2ac1b52a49454e6a2921aa54effee89eb958dc5ddbffbe 
        abi_file_path: ./abis/spark-orderbook.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: OpenOrderEvent
          - name: CancelOrderEvent
          - name: TradeOrderEvent
          - name: DepositEvent
          - name: WithdrawEvent
