name: OrderBook indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    hyperfuel_config:
       url: https://fuel-testnet.hypersync.xyz
    contracts:
      - name: MarketRegistry
        address: 0x0f5232e0d927f7a477baa7e6f0380c50f8b3de5c0d6ae42bb29ba8a767e5ff1a 
        abi_file_path: ./abis/spark-registry.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: MarketRegisterEvent
          # - name: MarketUnregisterEvent
      - name: OrderBook
        abi_file_path: ./abis/spark-orderbook.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: DepositEvent
          # - name: WithdrawEvent
          - name: OpenOrderEvent
          # - name: CancelOrderEvent
          # - name: TradeOrderEvent