name: OrderBook indexer
networks:
  - id: 0
    start_block: 0
    hypersync_config:
       url: https://fuel-testnet.hypersync.xyz
    contracts:
      - name: OrderBook
        address: 0x58959d086d8a6ee8cf8eeb572b111edb21661266be4b4885383748d11b72d0aa
        abi_file_path: ./abis/spark-orderbook.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: OpenOrderEvent
          - name: MatchOrderEvent
          - name: CancelOrderEvent
          - name: TradeOrderEvent
