
name: OrderBook indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    hyperfuel_config:
       url: https://fuel-testnet.hypersync.xyz
    contracts:
      - name: OrderBook
        address: [0xbc69e42348c9a992100970e8469247b58a517c2f7dd373741c6707cda35ccfc6, 0x10860c51de3a37c47ebff2e08a810d9e2963ef161ee3a88274520938c85914e8] 
        abi_file_path: ./abis/spark-orderbook.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: OpenOrderEvent
          - name: CancelOrderEvent
          - name: TradeOrderEvent
          - name: DepositEvent
          - name: WithdrawEvent
