name: OrderBook indexer
networks:
  - id: 0
    start_block: 0
    hypersync_config:
       url: https://fuel-testnet.hypersync.xyz
    contracts:
      - name: OrderBook
        address: 0xfb127ae7b328028f04c38c398d4b5b059bcdebd09218b1ec57a63cbdf17262ec
        abi_file_path: ./abis/spark-orderbook.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: OpenOrderEvent
          - name: CancelOrderEvent
          - name: TradeOrderEvent
          - name: DepositEvent
          - name: WithdrawEvent
