name: OrderBook
ecosystem: fuel
networks:
  - id: 9889
    start_block: 0
    contracts:
      - name: Registry
        address: 0xbb91b7f9d31ee562b24e35d756ce20913f9752600582f51008c63b2d3792926b
        abi_file_path: ./abis/registry.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: MarketRegisterEvent
      - name: Market
        abi_file_path: ./abis/market.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: DepositEvent
          - name: WithdrawEvent
          - name: WithdrawToMarketEvent
          - name: OpenOrderEvent
          - name: CancelOrderEvent
          - name: TradeOrderEvent