name: OrderBook indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    hyperfuel_config:
       url: https://fuel-testnet.hypersync.xyz
    contracts:
      - name: OrderBook
        address: 0x21cc465d074200e103a5de0488f6203509c9381eb642668454a7375c89368cf6 
        abi_file_path: ./abis/spark-orderbook.json
        handler: ./src/OrderBookHandlers.ts
        events:
          - name: OpenOrderEvent
          - name: CancelOrderEvent
          - name: TradeOrderEvent
          - name: DepositEvent
          - name: WithdrawEvent
